# Generated by Django 4.0.3 on 2022-03-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisasterAlerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.BigIntegerField(unique=True)),
                ('location', models.CharField(max_length=100)),
                ('event_title', models.CharField(max_length=100)),
                ('magnitude', models.CharField(max_length=100)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('expected_date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('coordinates', models.CharField(max_length=100)),
                ('event_type', models.CharField(choices=[('eathquake', 'eathquake'), ('cyclone', 'cyclone'), ('dought', 'drought'), ('floods', 'floods'), ('volcano', 'volcano'), ('wildFires', 'wildFires'), ('others', 'others')], default='others', max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('population', models.BigIntegerField()),
                ('alert_level', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.FloatField(default='')),
                ('longitude', models.FloatField(default='')),
            ],
        ),
    ]
