# Generated by Django 4.0.3 on 2022-03-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SendReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('lat', models.CharField(max_length=200)),
                ('long', models.CharField(max_length=200)),
                ('case', models.CharField(max_length=200)),
                ('createdAt', models.CharField(max_length=200)),
                ('report_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='DisasterAlerts',
        ),
    ]
